# Generated by Django 6.0.4 on 2026-04-10 03:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Frontend', 'Frontend Developer'), ('Backend', 'Backend Developer'), ('Fullstack', 'Full Stack Developer'), ('HR', 'HR Interview'), ('DSA', 'DSA / Problem Solving')], max_length=50)),
                ('level', models.CharField(choices=[('Fresher', 'Fresher'), ('Intermediate', 'Intermediate'), ('Senior', 'Senior')], max_length=50)),
                ('overall_score', models.IntegerField(default=0)),
                ('summary', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('answer_text', models.TextField(blank=True, null=True)),
                ('grammar_score', models.IntegerField(default=0)),
                ('confidence_score', models.IntegerField(default=0)),
                ('content_score', models.IntegerField(default=0)),
                ('feedback_good', models.TextField(blank=True, null=True)),
                ('feedback_improve', models.TextField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='api.interviewsession')),
            ],
        ),
    ]
