# Generated by Django 6.0.4 on 2026-04-10 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_interviewsession_selected_questions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewsession',
            name='resume_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
