QUESTIONS = {
    "Frontend": [
        "Explain the Virtual DOM in React and how it improves performance.",
        "What is the difference between == and === in JavaScript?",
        "How does event delegation work in JavaScript?",
        "What are React hooks? Explain useState and useEffect.",
        "What is the difference between var, let, and const?",
        "Explain CSS Flexbox vs Grid.",
        "How do you optimize a website for performance?",
        "What is lazy loading in frontend?",
        "What is the difference between controlled and uncontrolled components?",
        "How does browser rendering work?",
        "What is debounce and throttle?",
        "Explain closures in JavaScript.",
        "What is CORS and how do you fix it?",
        "What are semantic HTML tags?",
        "What is responsive design?",
        "Difference between localStorage and sessionStorage.",
        "Explain promises and async/await.",
        "What is JSX?",
        "What is state vs props in React?",
        "What is a SPA (Single Page Application)?",
        "How does React reconciliation work?",
        "What is hydration in frontend?",
        "What is Webpack?",
        "What is code splitting?",
        "What is tree shaking?",
        "Explain CSS specificity.",
        "What are pseudo-classes?",
        "What is accessibility (a11y)?",
        "What is SEO in frontend?",
        "Difference between inline, block, inline-block.",
        "What is shadow DOM?",
        "What is progressive web app (PWA)?",
        "How do you handle forms in React?",
        "What is Redux?",
        "What is context API?",
        "What is memoization?",
        "What is useMemo vs useCallback?",
        "What is SSR vs CSR?",
        "What is hydration error?",
        "What is tailwind CSS?",
        "Difference between bootstrap and tailwind.",
        "What is DOM?",
        "What is BOM?",
        "What is event bubbling vs capturing?",
        "What is service worker?",
        "What is Lighthouse?",
        "What is browser compatibility?",
        "What is CDN?",
        "What is minification?",
        "Explain a frontend project you built."
    ],
    "Backend": [
        "What is REST API?",
        "Difference between REST and GraphQL.",
        "What is middleware?",
        "Explain MVC architecture.",
        "What is JWT authentication?",
        "What is session vs token authentication?",
        "What is hashing?",
        "What is salting?",
        "What is database indexing?",
        "Difference between SQL and NoSQL.",
        "What is normalization?",
        "What is ACID properties?",
        "What is transaction?",
        "What is API rate limiting?",
        "What is caching?",
        "What is Redis?",
        "What is load balancing?",
        "What is microservices?",
        "What is monolithic architecture?",
        "What is Docker?",
        "What is CI/CD?",
        "What is environment variable?",
        "What is ORM?",
        "What is SQL injection?",
        "What is XSS attack?",
        "What is CSRF?",
        "What is HTTPS?",
        "What is server?",
        "What is reverse proxy?",
        "What is Nginx?",
        "What is API versioning?",
        "What is pagination?",
        "What is WebSocket?",
        "What is logging?",
        "What is error handling?",
        "What is cron job?",
        "What is queue system?",
        "What is message broker?",
        "What is scalability?",
        "What is fault tolerance?",
        "What is horizontal vs vertical scaling?",
        "What is REST status codes?",
        "What is API documentation?",
        "What is Swagger?",
        "What is dependency injection?",
        "What is file upload handling?",
        "What is streaming?",
        "What is authentication vs authorization?",
        "What is serverless?",
        "Explain backend project you built."
    ],
    "Fullstack": [
        "Explain full stack architecture.",
        "How frontend communicates with backend?",
        "What is REST API flow?",
        "How do you handle authentication?",
        "How do you deploy a full stack app?",
        "What is CORS issue?",
        "What is environment config?",
        "How do you connect database?",
        "What is CRUD operation?",
        "What is API integration?",
        "What is MVC pattern?",
        "What is MERN stack?",
        "What is LAMP stack?",
        "What is JWT flow?",
        "How do you secure APIs?",
        "What is role-based access?",
        "What is file upload system?",
        "What is cloud deployment?",
        "What is Git workflow?",
        "What is version control?",
        "What is API testing?",
        "What is Postman?",
        "What is error handling?",
        "What is logging system?",
        "What is caching?",
        "What is session management?",
        "What is form validation?",
        "What is real-time application?",
        "What is socket.io?",
        "What is pagination?",
        "What is search optimization?",
        "What is database schema?",
        "What is indexing?",
        "What is performance optimization?",
        "What is code splitting?",
        "What is SSR?",
        "What is SEO?",
        "What is Docker?",
        "What is CI/CD pipeline?",
        "What is AWS deployment?",
        "What is load balancing?",
        "What is scalability?",
        "What is microservices?",
        "What is debugging?",
        "What is monitoring?",
        "What is testing?",
        "What is unit test?",
        "What is integration test?",
        "What is end-to-end testing?",
        "Explain full stack project."
    ],
    "HR": [
        "Tell me about yourself.",
        "Why should we hire you?",
        "What are your strengths?",
        "What are your weaknesses?",
        "Why do you want this job?",
        "Where do you see yourself in 5 years?",
        "Tell me about a challenge you faced.",
        "Tell me about failure.",
        "How do you handle pressure?",
        "Why did you choose this field?",
        "What motivates you?",
        "What are your goals?",
        "Describe your leadership skills.",
        "Are you a team player?",
        "How do you handle conflict?",
        "What is your biggest achievement?",
        "What is your biggest mistake?",
        "Why did you leave your last job?",
        "What do you know about our company?",
        "What is your expected salary?",
        "Are you willing to relocate?",
        "What is your hobby?",
        "How do you manage time?",
        "How do you learn new skills?",
        "What makes you unique?",
        "What are your values?",
        "Describe your work ethic. ",
        "What is your dream job?",
        "What are your short-term goals?",
        "What are your long-term goals?",
        "How do you handle criticism?",
        "What is your biggest fear?",
        "How do you stay productive?",
        "Tell me about teamwork experience.",
        "Tell me about leadership experience.",
        "What is success for you?",
        "What is failure for you?",
        "What is your daily routine?",
        "Why should we not hire you?",
        "What do you expect from us?",
        "How do you prioritize work?",
        "What is your communication style?",
        "What are your salary expectations?",
        "How do you adapt to change?",
        "What is your biggest learning?",
        "What inspires you?",
        "What are your skills?",
        "How do you handle deadlines?",
        "Any questions for us?",
        "Give your self introduction."
    ],
    "DSA": [
        "Reverse a string.",
        "Find palindrome.",
        "Fibonacci series.",
        "Factorial using recursion.",
        "Check prime number.",
        "Find largest element in array.",
        "Find second largest.",
        "Remove duplicates.",
        "Sort array.",
        "Binary search.",
        "Linear search.",
        "Two sum problem.",
        "Merge two arrays.",
        "Rotate array.",
        "Find missing number.",
        "Count frequency.",
        "Find intersection.",
        "Kadane's algorithm.",
        "Longest substring.",
        "Valid parentheses.",
        "Stack implementation.",
        "Queue implementation.",
        "Linked list insertion.",
        "Linked list deletion.",
        "Reverse linked list.",
        "Detect cycle.",
        "Tree traversal.",
        "BFS.",
        "DFS.",
        "Binary tree height.",
        "Lowest common ancestor.",
        "Graph traversal.",
        "Dijkstra algorithm.",
        "Sorting algorithms.",
        "Time complexity.",
        "Space complexity.",
        "Recursion problems.",
        "Backtracking basics.",
        "N-Queens problem.",
        "Subset generation.",
        "Permutation generation.",
        "Dynamic programming basics.",
        "Knapsack problem.",
        "Longest common subsequence.",
        "Edit distance.",
        "Sliding window.",
        "Two pointer technique.",
        "Hashing usage.",
        "Greedy algorithm.",
        "Solve a real coding problem."
    ]
}
